### PR TITLE
removed/ commented out console.logs in all files

### PR DESCRIPTION
**Pull request by DannyMcwaves**
#103 
[working on removing webpack warning during build]

### CODE REVIEW

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman circleCI still return has the same `hawk` module error.

**Comment by JoshuaVSherman** [comment]
Please run the cleaninstall script the commit

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman error with `circleCI` install.

**Comment by JoshuaVSherman** [comment]
Please remove the eslint no console disabled run and push that commit so
that the eslint runs with that checker now, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman should the removal of `console.log` also apply to spec files. Almost all the warning generated are from the test spec files.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves yes, please

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves Thanks!

**Pull request merged**
