### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by DannyMcwaves**
eslint done.

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please fix merge conflict

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please fix the 3 failing unit tests, this was my fault, sorry

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I was planning to have a look at the tests today. I'd take care of it.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves the tests are still failing

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman circleCI is missing some modules. My current tests run just fine.

**Comment by JoshuaVSherman** [comment]
Ok I'll have to work on that next week

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves  pulled down your branch and yarn installed, got these warnings:
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning " > aurelia-tools@2.0.0" has incorrect peer dependency "babel-eslint@^7.2.3".
warning "karma-webpack > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves Ran npm test on my local dev and got the same errors from CircleCI:

 FAIL  test/jest-unit/Login_.spec.js
  ● Test suite failed to run

    Cannot find module 'hawk'
      
      at Object.<anonymous> (node_modules/request/request.js:9:12)

 FAIL  test/jest-unit/Register_.spec.js
  ● Test suite failed to run

    Cannot find module 'hawk'
      
      at Object.<anonymous> (node_modules/request/request.js:9:12)

 FAIL  test/jest-unit/User_.spec.js
  ● Test suite failed to run

    Cannot find module 'hawk'

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves from npm run cleaninstall, I got these warnings:
warning material-ui@1.0.0-beta.47: You can now upgrade to @material-ui/core
warning snyk > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning istanbul-combine > istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves npm test now works fine, it seems the node modules needed a refresh

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves this discussion has the answer in it, just fyi https://github.com/wmonk/create-react-app-typescript/issues/154

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Regarding https://github.com/WebJamApps/combined-front/issues/1127#issuecomment-391871854, we cannot upgrade material-ui beta.
screen shot 2018-05-27 at 7 18 27 am

the timer picker component depends on this version. Installing a `@material-ui/core` breaks the app.

screen shot 2018-05-27 at 7 31 50 am

Also, with `webpack-cli`, it's an issue with `jscodeshift`. it has to update it's dependencies.

**Comment by JoshuaVSherman** [comment]
Ok we will just follow the repo for updates, thanks

**Pull request merged**
