### PR TITLE
reactTest

### PR DESCRIPTION
**Pull request by JoshuaVSherman**
I got it to render, but there are console warnings...
Unhandled rejection Invariant Violation: Target container is not a DOM element.
    at invariant (webpack-internal:///85:42:15)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///214:16425:34)
    at Object.render (webpack-internal:///214:16513:12)
    at ReactTest.attached (webpack-internal:///react-test:40:55)
    at Controller.attached (webpack-internal:///7:3539:22)
    at View.attached (webpack-internal:///7:1584:23)
    at ViewSlot.attached (webpack-internal:///7:1947:13)
    at View.attached (webpack-internal:///7:1594:19)
    at ViewSlot.attached (webpack-internal:///7:1947:13)
    at eval (webpack-internal:///aurelia-framework:327:28)
From previous event:
    at Aurelia.setRoot (webpack-internal:///aurelia-framework:325:40)
    at eval (webpack-internal:///main:339:30)
From previous event:
    at Object._callee$ (webpack-internal:///main:338:29)
    at tryCatch (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js:4:1423)

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves Also, I have linter errors, so we need to change something with linter configurations for React or something, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Yh. I have actually seen the errors. I just wanted to make sure the functionality works first before making optimizations and fixing errors. I'm currently looking at this.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I think I just need to remove the stuff in react-test.js (I forgot to remove that)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I'll just head into work then and let you finish it up, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman great. I'll take care of it.

**Pull request closed without merging**
