### PR TITLE
WIP Music players

### PR DESCRIPTION
**Pull request by JoshuaVSherman**

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves darn so close, one karma test fails

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves If you just fix those song titles and do a few more unit tests, then i'll merge this into dev (after I test it locally), thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman which song titles. I fixed those.

**Comment by JoshuaVSherman** [comment]
All the ones on mission music page please

**Comment by DannyMcwaves** [comment]
do you mean the forward slash turned into a hyphen? the song name??

**Pull request merged**
